filter:
    excluded_paths:
        - 'vendors/*'
        - 'tests/phpunit/test_files/*'
tools:
    js_hint: true
    php_mess_detector: true
    php_code_coverage:
        test_command: 'phpunit -c phpunit.xml'
    php_cpd: true
    php_pdepend: true
    php_code_sniffer: true
    sensiolabs_security_checker: true
    php_hhvm: true